# Generated by Django 5.2.6 on 2025-10-06 07:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_system', '0006_alter_pendingcompany_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.SmallIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=23)),
                ('name', models.CharField(max_length=100)),
                ('status', models.SmallIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_system.companyinfo')),
                ('main_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='products.maingroup')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=23)),
                ('name', models.CharField(max_length=100)),
                ('status', models.SmallIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_system.companyinfo')),
                ('main_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.maingroup')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=23)),
                ('name', models.CharField(max_length=100)),
                ('status', models.SmallIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_system.companyinfo')),
                ('main_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturers', to='products.maingroup')),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=23)),
                ('unit_name', models.CharField(max_length=100)),
                ('status', models.SmallIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.manufacturer')),
                ('main_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='products.maingroup')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_code', models.CharField(max_length=100, unique=True)),
                ('group', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cp', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('mrp', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('status', models.SmallIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.manufacturer')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.forms')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.units')),
            ],
        ),
    ]
