# Generated by Django 5.2.6 on 2025-09-27 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='activated_by',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='is_active',
        ),
    ]
