# Generated by Django 5.2.6 on 2025-09-29 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0004_paymentmethod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
