# Generated by Django 5.2.6 on 2025-09-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0005_delete_userinfo_delete_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingcompany',
            name='company_name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='pendingcompany',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
