# Generated by Django 5.2.6 on 2025-10-07 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0006_alter_pendingcompany_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_system.companytype'),
        ),
    ]
