# Generated by Django 5.2.6 on 2025-10-07 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0007_alter_companyinfo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingcompany',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_system.companytype'),
        ),
    ]
