# Generated by Django 5.2.6 on 2025-10-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0008_alter_pendingcompany_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingcompany',
            name='company_id',
        ),
        migrations.AddField(
            model_name='pendingcompany',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
