# Generated by Django 5.2.6 on 2025-09-29 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_system', '0005_delete_userinfo_delete_userrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=11)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('address', models.TextField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('religion', models.CharField(blank=True, choices=[('Islam', 'Islam'), ('Hindu', 'Hindu'), ('Buddhism', 'Buddhism'), ('Christianity', 'Christianity'), ('Other', 'Other')], max_length=15, null=True)),
                ('nid', models.CharField(blank=True, max_length=100, null=True)),
                ('passport', models.CharField(blank=True, max_length=100, null=True)),
                ('driving_license', models.CharField(blank=True, max_length=100, null=True)),
                ('corporate_id', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_system.companyinfo')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.userrole')),
            ],
        ),
    ]
